//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Favorit.es_Extended.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favorite
    {
        public int FavoriteId { get; set; }
        public string UserId { get; set; }
        public string SmallUrl { get; set; }
        public string MediumUrl { get; set; }
        public string LargeUrl { get; set; }
        public string PhotoId { get; set; }
        public string Tags { get; set; }
    }
}
